platform :ios, '9.0'

inhibit_all_warnings!

target 'GoogleBooks' do
  use_frameworks!

    pod 'Alamofire', '~> 4.7'


  # Pods for GoogleBooks

  target 'GoogleBooksTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'GoogleBooksUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
